//! `loader.js` 骨架文本：新启动器（注入总线 · 方案 D）的默认写法。
//!
//! 与旧骨架的差别（2026-10-04）：
//!   - 不再教「每个 loader 一条 `--require`」：启动器只在 `NODE_OPTIONS` 里放一条
//!     `--require "mod-host.js"`，由总线按 `_launcher/mods/mod-plan.json` 的顺序 require 各 loader；
//!   - 改服务端源码的补丁统一走 `globalThis.__evejsMods.register()`（用 `SOURCE_PATCH` 开关），
//!     不再自己 hook `Module.prototype._compile` —— 多个模组各挂钩子会互相顶掉
//!     （2026-10-01 实测：自动挖矿与自动锁定自动集火抢 `handshake.js`）。
//!
//! 为什么单独一个文件：骨架 100+ 行 JS，混在 `scaffold.rs` 里会把业务逻辑淹掉。
//! `@ID@` / `@DISPLAY_NAME@` 是占位符，由 `scaffold.rs` 按 draft 替换；
//! 模板自己的 `SOURCE_PATCH` 值由 `ScaffoldTemplate::source_patch` 给，插在
//! `LOADER_HEAD` 与 `LOADER_MID` 之间。

/// 骨架前半：文件头 / 参数 / 源码补丁说明（到 `SOURCE_PATCH` 声明之前）
pub const LOADER_HEAD: &[&str] = &[
    "\"use strict\";",
    "/**",
    " * @DISPLAY_NAME@ —— EveJS 模组（kind: loader）",
    " * 由 EvEJS 启动器「创建模组」生成 · 骨架基准：MOD_AUTHORING.md 附录 B。",
    " *",
    " * 加载方式（新机制 · 注入总线）",
    " *   启动器只往服务端进程的 NODE_OPTIONS 里放一条 `--require`（启动器自带的注入总线），总线再按",
    " *   `_launcher/mods/mod-plan.json` 的顺序 require 本文件 —— 所以：",
    " *     · 模组目录带中文或空格都没问题（旧写法会拼进 NODE_OPTIONS，被转义/分词吃掉）；",
    " *     · NODE_OPTIONS 会被 npm → autostart.js → index.js 逐层继承，本文件在每个子进程里都会",
    " *       执行一次 —— 身份校验和「只装一次」判断必须保留。",
    " *",
    " * 要改服务端源码（不只是调接口）？走总线，不要自己 hook：",
    " *   globalThis.__evejsMods.register({ id, target, marker, slot, apply })",
    " *   🟥 四条约定：只用 register（别自己 hook Module.prototype._compile）、apply 只追加、",
    " *      marker 唯一、校验只校验改动前的前缀 —— 别拿整份文件 sha256（多层串链必然对不上）。",
    " *   开关就是下面的 SOURCE_PATCH：留 null 表示本模组不改服务端任何文件。",
    " */",
    "const path = require(\"path\");",
    "",
    "const TAG = \"[@ID@]\";",
    "const MOD_ID = \"@ID@\";",
    "/* ==== 可调参数 ==== */",
    "const POLL_MS = 3000;",
    "const WAIT_SERVER_MS = 500;",
    "const WAIT_SERVER_MAX_TRIES = 240;",
    "const GRACE_MS = 10000;",
    "const MESSAGE = \"欢迎回来，飞行员！本条消息由模组 @DISPLAY_NAME@ 发送。\";",
    "",
    "/* ==== 服务端源码补丁（选填 · 新机制）====",
    " * 需要改服务端文件时，把 SOURCE_PATCH 填成这个形状：",
    " *   const SOURCE_PATCH = {",
    " *     target: \"server/src/…/目标文件.js\",            // 相对 EveJS 根目录，正斜杠",
    " *     marker: \"// @ID@:patch\",                      // 唯一标记：已注入就跳过",
    " *     slot: 40,                                     // 同文件多层补丁的先后，越小越前",
    " *     append: \"// @ID@:patch\\nconsole.log('[@ID@] 已注入');\",  // 只追加的代码",
    " *   };",
    " * 只调用服务端 API 的模组（本模板的欢迎消息就是）保持 null 即可。",
    " */",
];

/// 骨架中段：`SOURCE_PATCH` 声明之后（到业务钩子之前）
pub const LOADER_MID: &[&str] = &[
    "",
    "console.log(TAG + \" preload 已执行 · pid=\" + process.pid);",
    "",
    "/** 兼容写法：部分环境下 require.main 在 preload 阶段尚未就绪 */",
    "function entryFile() {",
    "  try {",
    "    return require.main && require.main.filename ? require.main.filename : \"\";",
    "  } catch {",
    "    return \"\";",
    "  }",
    "}",
    "",
    "/** 只在真正的服务端进程里继续（排除 npm / autostart.js 包装进程） */",
    "function isRealServerProcess(entry) {",
    "  if (process.env.EVEJS_GAMESTORE_OWNER_ROLE === \"world\") return true;",
    "  return /(^|[\\\\/])index\\.js$/i.test(entry);",
    "}",
    "",
    "// 新机制：源码补丁必须在这里同步注册 —— 服务端启动期就会 require 目标文件，",
    "// 放进 setImmediate 里再注册就晚了（文件已经编译过，补丁不会生效）。",
    "registerSourcePatch();",
    "",
    "setImmediate(() => {",
    "  const entry = entryFile();",
    "  if (!isRealServerProcess(entry)) {",
    "    console.log(TAG + \" 跳过包装进程（entry=\" + (entry || \"?\") + \"）\");",
    "    return;",
    "  }",
    "  start(entry);",
    "});",
    "",
    "function start(entry) {",
    "  if (globalThis.__EVEJS_SCAFFOLD_STARTED__) {",
    "    console.log(TAG + \" 已启动过，忽略重复加载\");",
    "    return;",
    "  }",
    "  globalThis.__EVEJS_SCAFFOLD_STARTED__ = true;",
    "",
    "  const serverRoot = path.resolve(__dirname, \"..\", \"..\", \"server\");",
    "",
    "  whenServerChatLoaded(serverRoot, (sessionRegistry, chatHub) => {",
];

/// `template.id == "blank"` 的业务钩子
pub const LOADER_BIZ_BLANK: &[&str] = &[
    "    /* TODO: 业务逻辑写在这里。",
    "       下面是可用的实测接口：",
    "         sessionRegistry.getSessions()                     -> 在线会话数组",
    "         sessionRegistry.resolveSessionCharacterID(s)      -> 角色 ID（未进入游戏时为 0）",
    "         chatHub.sendSystemMessage(session, \"消息\")        -> 在该角色本地频道发系统消息",
    "       要改服务端源码就填文件顶部的 SOURCE_PATCH（走注入总线），不要自己 hook _compile；",
    "       改完记得重启主服务器，然后在游戏里验证。 */",
    "    console.log(TAG + \" 已启用（空白骨架）\");",
];

/// 默认（broadcast）的业务钩子
pub const LOADER_BIZ_BROADCAST: &[&str] = &[
    "    const seen = new Set();",
    "    const firstSeenAt = new Map();",
    "    globalThis.__EVEJS_SCAFFOLD_HOOK__ = { seen, firstSeenAt };",
    "",
    "    console.log(TAG + \" 已启用 · 每 \" + POLL_MS / 1000 + \" 秒扫描 · 上线 \" + GRACE_MS / 1000 + \" 秒后发送\");",
    "",
    "    const timer = setInterval(() => {",
    "      let sessions;",
    "      try {",
    "        sessions = sessionRegistry.getSessions() || [];",
    "      } catch {",
    "        return;",
    "      }",
    "",
    "      const now = Date.now();",
    "      const online = new Set();",
    "",
    "      for (const session of sessions) {",
    "        let characterID = 0;",
    "        try {",
    "          characterID = sessionRegistry.resolveSessionCharacterID(session);",
    "        } catch {",
    "          characterID = 0;",
    "        }",
    "        // 角色还没真正进入游戏（characterID 还是 0）时跳过，等下一轮",
    "        if (!characterID) continue;",
    "        online.add(characterID);",
    "",
    "        if (!firstSeenAt.has(characterID)) firstSeenAt.set(characterID, now);",
    "        if (seen.has(characterID)) continue;",
    "        if (now - firstSeenAt.get(characterID) < GRACE_MS) continue;",
    "",
    "        // sendSystemMessage 内部只认 session.characterID，",
    "        // 有些会话对象只带小写 charid，这里补一次，避免\"静默不发送\"。",
    "        try {",
    "          if (!Number(session.characterID || 0)) session.characterID = characterID;",
    "        } catch {",
    "          /* 只读对象就跳过这一步 */",
    "        }",
    "",
    "        try {",
    "          chatHub.sendSystemMessage(session, MESSAGE);",
    "          seen.add(characterID);",
    "          console.log(TAG + \" 已向角色 \" + characterID + \" 发送消息\");",
    "        } catch (error) {",
    "          console.log(TAG + \" 角色 \" + characterID + \" 尚未就绪，稍后重试：\" + error.message);",
    "        }",
    "      }",
    "",
    "      // 下线的角色清理掉，下次登录会重新触发",
    "      for (const characterID of Array.from(seen)) {",
    "        if (!online.has(characterID)) seen.delete(characterID);",
    "      }",
    "      for (const characterID of Array.from(firstSeenAt.keys())) {",
    "        if (!online.has(characterID)) firstSeenAt.delete(characterID);",
    "      }",
    "    }, POLL_MS);",
    "",
    "    if (timer && typeof timer.unref === \"function\") timer.unref();",
];

/// 骨架后半：`start()` 收尾 + `registerSourcePatch()` + `whenServerChatLoaded()`
pub const LOADER_TAIL: &[&str] = &[
    "  });",
    "}",
    "",
    "/**",
    " * 把本模组的服务端源码补丁注册到注入总线（新机制 · 方案 D）。",
    " * 老启动器没有总线（globalThis.__evejsMods 缺席）时只提示、不注入。",
    " */",
    "function registerSourcePatch() {",
    "  if (!SOURCE_PATCH || !SOURCE_PATCH.target) return;",
    "  const bus = globalThis.__evejsMods;",
    "  if (!bus || typeof bus.register !== \"function\" || !(Number(bus.api) >= 1)) {",
    "    console.log(TAG + \" 未检测到注入总线（老启动器），本次不注入源码补丁：\" + SOURCE_PATCH.target);",
    "    return;",
    "  }",
    "  const marker = SOURCE_PATCH.marker || (\"// \" + MOD_ID + \":patch\");",
    "  const result = bus.register({",
    "    id: MOD_ID,",
    "    target: SOURCE_PATCH.target,",
    "    marker: marker,",
    "    slot: Number.isFinite(SOURCE_PATCH.slot) ? SOURCE_PATCH.slot : 100,",
    "    apply: function (source) {",
    "      return source + \"\\n\" + SOURCE_PATCH.append + \"\\n\";",
    "    },",
    "  });",
    "  if (result && result.ok) {",
    "    console.log(TAG + \" 已向注入总线注册源码补丁：\" + SOURCE_PATCH.target);",
    "  } else {",
    "    console.log(TAG + \" 源码补丁注册被拒绝：\" + String((result && result.reason) || \"未知原因\"));",
    "  }",
    "}",
    "",
    "/** 等服务端自己把 chatHub 加载进 require.cache，再取引用（零额外内存、无第二份实例） */",
    "function whenServerChatLoaded(serverRoot, callback) {",
    "  const hubPath = path.join(serverRoot, \"src\", \"services\", \"chat\", \"chatHub.js\");",
    "  const registryPath = path.join(serverRoot, \"src\", \"services\", \"chat\", \"sessionRegistry.js\");",
    "",
    "  let hubResolved = null;",
    "  let registryResolved = null;",
    "  try {",
    "    hubResolved = require.resolve(hubPath);",
    "    registryResolved = require.resolve(registryPath);",
    "  } catch (error) {",
    "    console.error(TAG + \" 找不到服务端聊天模块，模组未生效：\" + error.message);",
    "    return;",
    "  }",
    "",
    "  let tries = 0;",
    "  const timer = setInterval(() => {",
    "    tries += 1;",
    "    if (!require.cache[hubResolved] || !require.cache[registryResolved]) {",
    "      if (tries >= WAIT_SERVER_MAX_TRIES) {",
    "        clearInterval(timer);",
    "        console.log(TAG + \" 等待服务端加载聊天模块超时（\" + WAIT_SERVER_MAX_TRIES * WAIT_SERVER_MS / 1000 + \"s），模组未生效\");",
    "      }",
    "      return;",
    "    }",
    "",
    "    clearInterval(timer);",
    "    try {",
    "      callback(require(registryResolved), require(hubResolved));",
    "    } catch (error) {",
    "      console.error(TAG + \" 加载服务端聊天模块失败：\" + error.message);",
    "    }",
    "  }, WAIT_SERVER_MS);",
    "",
    "  if (timer && typeof timer.unref === \"function\") timer.unref();",
    "}",
    "",
];
