//! `loader.js` 骨架文本：从现役版 `modScaffold.ts::loaderFrom` 自动抽取，逐字节一致。
//!
//! 生成方式（一次性，改了现役版骨架才需要重跑）：
//!   `node scripts/extract-loader-skeleton.mjs`
//!
//! 为什么单独一个文件：骨架 100+ 行 JS，混在 `scaffold.rs` 里会把业务逻辑淹掉。
//! `@ID@` / `@DISPLAY_NAME@` 是占位符，由 `scaffold.rs` 按 draft 替换。

/// 骨架前半（`biz` 之前）
pub const LOADER_HEAD: &[&str] = &[
    "\"use strict\";",
    "/**",
    " * @DISPLAY_NAME@ —— EveJS 模组（kind: loader）",
    " * 由 EvEJS 启动器「创建模组」生成，骨架基准：mods/welcome-mod（= MOD_AUTHORING.md §6）。",
    " *",
    " * 原理：服务端就是同一个 Node 进程。Node 有模块缓存，loader 里 require 同一个服务端模块",
    " *   拿到的是**同一个实例**，所以可以直接调用服务端内部 API，而完全不需要修改服务端任何文件。",
    " *",
    " * 三处必须保留的写法（删掉任何一处都会出问题）：",
    " *   1) setImmediate + require.main.filename 身份校验 —— NODE_OPTIONS 会被",
    " *      npm(node) → node autostart.js → node .（真正的服务端）逐层继承，每层都会加载本文件，",
    " *      只在真正的服务端进程里启动逻辑；",
    " *   2) **不要直接 require 服务端大模块**（chatHub 会拉起约 456MB / 645 个模块），",
    " *      而是等 require.cache 里出现它之后再取引用，此时是缓存命中、零额外内存；",
    " *   3) timer.unref() —— 不让定时器阻止进程退出。",
    " */",
    "",
    "const path = require(\"path\");",
    "",
    "const TAG = \"[@ID@]\";",
    "/* ==== 可调参数 ==== */",
    "const POLL_MS = 3000;",
    "const WAIT_SERVER_MS = 500;",
    "const WAIT_SERVER_MAX_TRIES = 240;",
    "const GRACE_MS = 10000;",
    "const MESSAGE = \"欢迎回来，飞行员！本条消息由模组 @DISPLAY_NAME@ 发送。\";",
    "",
    "console.log(TAG + \" preload 已执行 · pid=\" + process.pid);",
    "",
    "/** 兼容写法：部分环境下 require.main 在 preload 阶段尚未就绪 */",
    "function entryFile() {",
    "  try {",
    "    return require.main && require.main.filename ? require.main.filename : \"\";",
    "  } catch {",
    "    return \"\";",
    "  }",
    "}",
    "",
    "/** 只在真正的服务端进程里继续（排除 npm / autostart.js 包装进程） */",
    "function isRealServerProcess(entry) {",
    "  if (process.env.EVEJS_GAMESTORE_OWNER_ROLE === \"world\") return true;",
    "  return /(^|[\\\\/])index\\.js$/i.test(entry);",
    "}",
    "",
    "setImmediate(() => {",
    "  const entry = entryFile();",
    "  if (!isRealServerProcess(entry)) {",
    "    console.log(TAG + \" 跳过包装进程（entry=\" + (entry || \"?\") + \"）\");",
    "    return;",
    "  }",
    "  start(entry);",
    "});",
    "",
    "function start(entry) {",
    "  if (globalThis.__EVEJS_SCAFFOLD_STARTED__) {",
    "    console.log(TAG + \" 已启动过，忽略重复加载\");",
    "    return;",
    "  }",
    "  globalThis.__EVEJS_SCAFFOLD_STARTED__ = true;",
    "",
    "  const serverRoot = path.resolve(__dirname, \"..\", \"..\", \"server\");",
    "",
    "  whenServerChatLoaded(serverRoot, (sessionRegistry, chatHub) => {",
];

/// `template.id == "blank"` 的业务钩子
pub const LOADER_BIZ_BLANK: &[&str] = &[
    "    /* TODO: 业务逻辑写在这里。",
    "       下面是可用的实测接口：",
    "         sessionRegistry.getSessions()                     -> 在线会话数组",
    "         sessionRegistry.resolveSessionCharacterID(s)      -> 角色 ID（未进入游戏时为 0）",
    "         chatHub.sendSystemMessage(session, \"消息\")        -> 在该角色本地频道发系统消息",
    "       改完记得重启主服务器，然后在游戏里验证。 */",
    "    console.log(TAG + \" 已启用（空白骨架）\");",
];

/// 默认（broadcast）的业务钩子
pub const LOADER_BIZ_BROADCAST: &[&str] = &[
    "    const seen = new Set();",
    "    const firstSeenAt = new Map();",
    "    globalThis.__EVEJS_SCAFFOLD_HOOK__ = { seen, firstSeenAt };",
    "",
    "    console.log(TAG + \" 已启用 · 每 \" + POLL_MS / 1000 + \" 秒扫描 · 上线 \" + GRACE_MS / 1000 + \" 秒后发送\");",
    "",
    "    const timer = setInterval(() => {",
    "      let sessions;",
    "      try {",
    "        sessions = sessionRegistry.getSessions() || [];",
    "      } catch {",
    "        return;",
    "      }",
    "",
    "      const now = Date.now();",
    "      const online = new Set();",
    "",
    "      for (const session of sessions) {",
    "        let characterID = 0;",
    "        try {",
    "          characterID = sessionRegistry.resolveSessionCharacterID(session);",
    "        } catch {",
    "          characterID = 0;",
    "        }",
    "        // 角色还没真正进入游戏（characterID 还是 0）时跳过，等下一轮",
    "        if (!characterID) continue;",
    "        online.add(characterID);",
    "",
    "        if (!firstSeenAt.has(characterID)) firstSeenAt.set(characterID, now);",
    "        if (seen.has(characterID)) continue;",
    "        if (now - firstSeenAt.get(characterID) < GRACE_MS) continue;",
    "",
    "        // sendSystemMessage 内部只认 session.characterID，",
    "        // 有些会话对象只带小写 charid，这里补一次，避免\"静默不发送\"。",
    "        try {",
    "          if (!Number(session.characterID || 0)) session.characterID = characterID;",
    "        } catch {",
    "          /* 只读对象就跳过这一步 */",
    "        }",
    "",
    "        try {",
    "          chatHub.sendSystemMessage(session, MESSAGE);",
    "          seen.add(characterID);",
    "          console.log(TAG + \" 已向角色 \" + characterID + \" 发送消息\");",
    "        } catch (error) {",
    "          console.log(TAG + \" 角色 \" + characterID + \" 尚未就绪，稍后重试：\" + error.message);",
    "        }",
    "      }",
    "",
    "      // 下线的角色清理掉，下次登录会重新触发",
    "      for (const characterID of Array.from(seen)) {",
    "        if (!online.has(characterID)) seen.delete(characterID);",
    "      }",
    "      for (const characterID of Array.from(firstSeenAt.keys())) {",
    "        if (!online.has(characterID)) firstSeenAt.delete(characterID);",
    "      }",
    "    }, POLL_MS);",
    "",
    "    if (timer && typeof timer.unref === \"function\") timer.unref();",
];

/// 骨架后半（`biz` 之后）
pub const LOADER_TAIL: &[&str] = &[
    "  });",
    "}",
    "",
    "/** 等服务端自己把 chatHub 加载进 require.cache，再取引用（零额外内存、无第二份实例） */",
    "function whenServerChatLoaded(serverRoot, callback) {",
    "  const hubPath = path.join(serverRoot, \"src\", \"services\", \"chat\", \"chatHub.js\");",
    "  const registryPath = path.join(serverRoot, \"src\", \"services\", \"chat\", \"sessionRegistry.js\");",
    "",
    "  let hubResolved = null;",
    "  let registryResolved = null;",
    "  try {",
    "    hubResolved = require.resolve(hubPath);",
    "    registryResolved = require.resolve(registryPath);",
    "  } catch (error) {",
    "    console.error(TAG + \" 找不到服务端聊天模块，模组未生效：\" + error.message);",
    "    return;",
    "  }",
    "",
    "  let tries = 0;",
    "  const timer = setInterval(() => {",
    "    tries += 1;",
    "    if (!require.cache[hubResolved] || !require.cache[registryResolved]) {",
    "      if (tries >= WAIT_SERVER_MAX_TRIES) {",
    "        clearInterval(timer);",
    "        console.log(TAG + \" 等待服务端加载聊天模块超时（\" + WAIT_SERVER_MAX_TRIES * WAIT_SERVER_MS / 1000 + \"s），模组未生效\");",
    "      }",
    "      return;",
    "    }",
    "",
    "    clearInterval(timer);",
    "    try {",
    "      callback(require(registryResolved), require(hubResolved));",
    "    } catch (error) {",
    "      console.error(TAG + \" 加载服务端聊天模块失败：\" + error.message);",
    "    }",
    "  }, WAIT_SERVER_MS);",
    "",
    "  if (timer && typeof timer.unref === \"function\") timer.unref();",
    "}",
    "",
];
